/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChallengeIndexRouteImport } from './routes/challenge/index'
import { Route as ChallengeRegisterRouteImport } from './routes/challenge/register'
import { Route as ChallengeDashboardRouteImport } from './routes/challenge/dashboard'
import { Route as ApiTeamGetRouteImport } from './routes/api/team/get'
import { Route as ApiTeamCreateRouteImport } from './routes/api/team/create'
import { Route as ApiTeamCheckRegistrationRouteImport } from './routes/api/team/check-registration'
import { Route as ApiRegistrationStatusRouteImport } from './routes/api/registration/status'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeIndexRoute = ChallengeIndexRouteImport.update({
  id: '/challenge/',
  path: '/challenge/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRegisterRoute = ChallengeRegisterRouteImport.update({
  id: '/challenge/register',
  path: '/challenge/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeDashboardRoute = ChallengeDashboardRouteImport.update({
  id: '/challenge/dashboard',
  path: '/challenge/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamGetRoute = ApiTeamGetRouteImport.update({
  id: '/api/team/get',
  path: '/api/team/get',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamCreateRoute = ApiTeamCreateRouteImport.update({
  id: '/api/team/create',
  path: '/api/team/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamCheckRegistrationRoute =
  ApiTeamCheckRegistrationRouteImport.update({
    id: '/api/team/check-registration',
    path: '/api/team/check-registration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRegistrationStatusRoute = ApiRegistrationStatusRouteImport.update({
  id: '/api/registration/status',
  path: '/api/registration/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/challenge/dashboard': typeof ChallengeDashboardRoute
  '/challenge/register': typeof ChallengeRegisterRoute
  '/challenge': typeof ChallengeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/registration/status': typeof ApiRegistrationStatusRoute
  '/api/team/check-registration': typeof ApiTeamCheckRegistrationRoute
  '/api/team/create': typeof ApiTeamCreateRoute
  '/api/team/get': typeof ApiTeamGetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/challenge/dashboard': typeof ChallengeDashboardRoute
  '/challenge/register': typeof ChallengeRegisterRoute
  '/challenge': typeof ChallengeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/registration/status': typeof ApiRegistrationStatusRoute
  '/api/team/check-registration': typeof ApiTeamCheckRegistrationRoute
  '/api/team/create': typeof ApiTeamCreateRoute
  '/api/team/get': typeof ApiTeamGetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/challenge/dashboard': typeof ChallengeDashboardRoute
  '/challenge/register': typeof ChallengeRegisterRoute
  '/challenge/': typeof ChallengeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/registration/status': typeof ApiRegistrationStatusRoute
  '/api/team/check-registration': typeof ApiTeamCheckRegistrationRoute
  '/api/team/create': typeof ApiTeamCreateRoute
  '/api/team/get': typeof ApiTeamGetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/challenge/dashboard'
    | '/challenge/register'
    | '/challenge'
    | '/api/auth/$'
    | '/api/registration/status'
    | '/api/team/check-registration'
    | '/api/team/create'
    | '/api/team/get'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/challenge/dashboard'
    | '/challenge/register'
    | '/challenge'
    | '/api/auth/$'
    | '/api/registration/status'
    | '/api/team/check-registration'
    | '/api/team/create'
    | '/api/team/get'
  id:
    | '__root__'
    | '/'
    | '/challenge/dashboard'
    | '/challenge/register'
    | '/challenge/'
    | '/api/auth/$'
    | '/api/registration/status'
    | '/api/team/check-registration'
    | '/api/team/create'
    | '/api/team/get'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChallengeDashboardRoute: typeof ChallengeDashboardRoute
  ChallengeRegisterRoute: typeof ChallengeRegisterRoute
  ChallengeIndexRoute: typeof ChallengeIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRegistrationStatusRoute: typeof ApiRegistrationStatusRoute
  ApiTeamCheckRegistrationRoute: typeof ApiTeamCheckRegistrationRoute
  ApiTeamCreateRoute: typeof ApiTeamCreateRoute
  ApiTeamGetRoute: typeof ApiTeamGetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge/': {
      id: '/challenge/'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge/register': {
      id: '/challenge/register'
      path: '/challenge/register'
      fullPath: '/challenge/register'
      preLoaderRoute: typeof ChallengeRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge/dashboard': {
      id: '/challenge/dashboard'
      path: '/challenge/dashboard'
      fullPath: '/challenge/dashboard'
      preLoaderRoute: typeof ChallengeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/get': {
      id: '/api/team/get'
      path: '/api/team/get'
      fullPath: '/api/team/get'
      preLoaderRoute: typeof ApiTeamGetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/create': {
      id: '/api/team/create'
      path: '/api/team/create'
      fullPath: '/api/team/create'
      preLoaderRoute: typeof ApiTeamCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/check-registration': {
      id: '/api/team/check-registration'
      path: '/api/team/check-registration'
      fullPath: '/api/team/check-registration'
      preLoaderRoute: typeof ApiTeamCheckRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registration/status': {
      id: '/api/registration/status'
      path: '/api/registration/status'
      fullPath: '/api/registration/status'
      preLoaderRoute: typeof ApiRegistrationStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChallengeDashboardRoute: ChallengeDashboardRoute,
  ChallengeRegisterRoute: ChallengeRegisterRoute,
  ChallengeIndexRoute: ChallengeIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRegistrationStatusRoute: ApiRegistrationStatusRoute,
  ApiTeamCheckRegistrationRoute: ApiTeamCheckRegistrationRoute,
  ApiTeamCreateRoute: ApiTeamCreateRoute,
  ApiTeamGetRoute: ApiTeamGetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
